# Generated by Django 5.0.7 on 2024-08-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='family_code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
