# Generated by Django 5.0.3 on 2024-08-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='family_code',
            field=models.CharField(default='TEMP', max_length=6, unique=True),
        ),
        migrations.DeleteModel(
            name='FamilyInvitation',
        ),
    ]
