# Generated by Django 5.0.3 on 2024-08-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_family_family_code_delete_familyinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='family_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
