# Generated by Django 5.0.7 on 2024-07-31 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_video_album_remove_video_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='shared',
        ),
    ]
