# Generated by Django 5.0.3 on 2024-07-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photovideolike_delete_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
    ]
