# Generated by Django 5.0.7 on 2024-08-01 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_tag_photo_title_photo_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
