# Generated by Django 5.0.7 on 2024-08-02 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_remove_photo_tags_delete_tag'),
        ('users', '0003_remove_family_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='users.family'),
        ),
    ]
