# Generated by Django 5.0.7 on 2024-07-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kakao_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
