# Generated by Django 5.0.7 on 2024-07-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_kakao_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
