# Generated by Django 5.0.7 on 2024-07-30 17:42

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='description',
            new_name='emoji',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='reminder_time',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='type',
        ),
        migrations.AddField(
            model_name='calendar',
            name='emoji_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='calendar',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='calendar_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendar',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 17, 42, 58, 968565, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendar',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
