# Generated by Django 5.0.7 on 2024-07-28 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_familyinvitation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamilyInvitation',
        ),
    ]
