# Generated by Django 5.0.7 on 2024-08-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_appointment_family_challenge_family_challenge_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='challenges/'),
        ),
    ]
