# Generated by Django 5.0.7 on 2024-08-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_remove_appointment_family_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
