# Generated by Django 5.0.7 on 2024-08-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_remove_appointment_patient_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='dinner',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='medication',
            name='lunch',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='medication',
            name='morning',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
