# Generated by Django 5.0.7 on 2024-08-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('볼거리', '볼거리'), ('놀거리', '놀거리'), ('배울거리', '배울거리'), ('추억거리', '추억거리')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(choices=[('Life', 'Life'), ('Hobby', 'Hobby'), ('Cook', 'Cook'), ('Activity', 'Activity'), ('Play', 'Play'), ('Temapark', 'Temapark'), ('Movie', 'Movie'), ('Show', 'Show'), ('Art', 'Art'), ('Local', 'Local'), ('Abroad', 'Abroad'), ('Hotel', 'Hotel')], max_length=255),
        ),
    ]
