# Generated by Django 5.0.7 on 2024-08-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0002_culturalactivity_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturalactivity',
            name='date',
        ),
        migrations.RemoveField(
            model_name='culturalactivity',
            name='family',
        ),
        migrations.AddField(
            model_name='culturalactivity',
            name='distance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='culturalactivity',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='culturalactivity',
            name='hyperlink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='culturalactivity',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='culturalactivity',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
