# Generated by Django 5.0.3 on 2024-07-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0003_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
    ]
