# Generated by Django 5.0.7 on 2024-07-29 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0005_category_remove_culturalactivity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalactivity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='culture.category'),
        ),
        migrations.AlterField(
            model_name='culturalactivity',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='culture.subcategory'),
        ),
    ]
