# Generated by Django 5.0.7 on 2024-07-29 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0006_alter_culturalactivity_category_and_more'),
        ('users', '0002_remove_family_members_remove_family_invite_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalactivity',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.family'),
        ),
    ]
